// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  firstName, lastName, email, phone, age, user_status
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING userid, firstname, lastname, email, phone, age, user_status
`

type CreateUserParams struct {
	Firstname  string
	Lastname   string
	Email      string
	Phone      pgtype.Text
	Age        pgtype.Int4
	UserStatus NullUserstatus
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Firstname,
		arg.Lastname,
		arg.Email,
		arg.Phone,
		arg.Age,
		arg.UserStatus,
	)
	var i User
	err := row.Scan(
		&i.Userid,
		&i.Firstname,
		&i.Lastname,
		&i.Email,
		&i.Phone,
		&i.Age,
		&i.UserStatus,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE userId = $1
`

func (q *Queries) DeleteUser(ctx context.Context, userid int32) error {
	_, err := q.db.Exec(ctx, deleteUser, userid)
	return err
}

const getUser = `-- name: GetUser :one
SELECT userid, firstname, lastname, email, phone, age, user_status FROM users
WHERE userId = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, userid int32) (User, error) {
	row := q.db.QueryRow(ctx, getUser, userid)
	var i User
	err := row.Scan(
		&i.Userid,
		&i.Firstname,
		&i.Lastname,
		&i.Email,
		&i.Phone,
		&i.Age,
		&i.UserStatus,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT userid, firstname, lastname, email, phone, age, user_status FROM users
ORDER BY firstName
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.Userid,
			&i.Firstname,
			&i.Lastname,
			&i.Email,
			&i.Phone,
			&i.Age,
			&i.UserStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
  set 
  firstName = $2,
  lastName = $3,
  email = $4,
  phone = $5,
  age = $6,
  user_status = $7
WHERE userId = $1
`

type UpdateUserParams struct {
	Userid     int32
	Firstname  string
	Lastname   string
	Email      string
	Phone      pgtype.Text
	Age        pgtype.Int4
	UserStatus NullUserstatus
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.Userid,
		arg.Firstname,
		arg.Lastname,
		arg.Email,
		arg.Phone,
		arg.Age,
		arg.UserStatus,
	)
	return err
}
